Repository GolosChain/golos, pull requests merged in 2018-11, with the labels that each got.

#983 Added pagging in getting active votes #981
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/discussion_helper.hpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/social_network/social_network.cpp
  plugins/tags/include/golos/plugins/tags/discussion_query.hpp
  plugins/tags/plugin.cpp
Labels: API changes, optional

#991 fixed bug when calculating private messages counters
  plugins/private_message/private_message_plugin.cpp
  tests/plugin_tests/private_message.cpp
Labels: bug

#993 Add auction_window_reward_operation #992
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_operations.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/mongo_db_operations.cpp
  plugins/mongo_db/mongo_db_state.cpp
Labels: bug, low, softfork
