Repository GolosChain/golos, pull requests merged in 2018-06, with the labels that each got.

#695 Add limits on nested proposals. #687
  libraries/chain/include/golos/chain/steem_evaluator.hpp
  libraries/chain/proposal_evaluator.cpp
  libraries/protocol/include/golos/protocol/config.hpp
Labels: core, enhancement, hardfork, high

#696 Duplicate property updates. #693
  libraries/chain/chain_properties_evaluators.cpp
  libraries/chain/database.cpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  tests/tests/operation_tests.cpp
Labels: enhancement, medium

#698 Change default value for GOLOS_CREATE_ACCOUNT_WITH_GOLOS_MODIFIER to …
  libraries/protocol/include/golos/protocol/config.hpp
Labels: core, enhancement, high

#705 Remove old account_bandwidth
  libraries/api/account_api_object.cpp
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/account_api_object.hpp
  libraries/api/include/golos/api/discussion_helper.hpp
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/steem_object_types.hpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/config.hpp
  libraries/protocol/include/golos/protocol/operations.hpp
  libraries/protocol/include/golos/protocol/steem_operations.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/auth_util/include/golos/plugins/auth_util/plugin.hpp
  plugins/debug_node/plugin.cpp
  plugins/follow/include/golos/plugins/follow/plugin.hpp
  plugins/operation_history/plugin.cpp
  programs/cli_wallet/main.cpp
  tests/tests/operation_tests.cpp
  tests/tests/proposal_tests.cpp
Labels: core, enhancement, hardfork

#706 702 mongo root comment
  plugins/mongo_db/mongo_db_state.cpp
Labels: enhancement, medium

#707 688 get discussions by promoted returns nothing
  plugins/tags/plugin.cpp
Labels: bug, core

#710 Fix updating of tags after cashout window. #708
  plugins/tags/include/golos/plugins/tags/tag_visitor.hpp
  plugins/tags/tag_visitor.cpp
Labels: API changes, bug, high

#712 Change HF18 time to 20 Jun 2018. #711
  libraries/chain/hardfork.d/0_18.hf
Labels: core, hardfork

#716 Mongo_db Add transfer_operation implementation #703
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_types.hpp
  plugins/mongo_db/mongo_db_state.cpp
  plugins/mongo_db/mongo_db_writer.cpp
Labels: enhancement, medium

#718 Fetch witness.url in cli_wallet update_witness command only if needed #713
  libraries/wallet/wallet.cpp
Labels: enhancement

#720 Mongo_db Add account_object collection #704
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/mongo_db_state.cpp
Labels: enhancement, medium

#728 Simplify delegation parameters + related fixes
  libraries/api/chain_api_properties.cpp
  libraries/api/include/golos/api/chain_api_properties.hpp
  libraries/chain/database.cpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/steem_operations.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  tests/tests/operation_tests.cpp
Labels: bug, core, enhancement

#731 Change default cli_wallet ports to conform golosd #730
  libraries/wallet/include/golos/wallet/wallet.hpp
  programs/cli_wallet/main.cpp
Labels: cli_wallet, enhancement

#732 Golos v0.18.0
  libraries/wallet/include/golos/wallet/wallet.hpp
  programs/cli_wallet/main.cpp
Labels: cli_wallet, enhancement

#735 Fix nested comments in get_all_content_replies. #733
  plugins/social_network/social_network.cpp
Labels: API changes, bug, high

#736 Golos v0.18.0
  plugins/social_network/social_network.cpp
Labels: API changes, bug, high

#734 Mongo_db Added more subjects and modifying behaviour for them #719
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_types.hpp
  plugins/mongo_db/mongo_db_state.cpp
Labels: enhancement, medium

#747 Mongo_db Added global_property_object and witness_schedule_object for…
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_types.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_writer.hpp
  plugins/mongo_db/mongo_db_state.cpp
  plugins/mongo_db/mongo_db_writer.cpp
Labels: enhancement, medium

#749 Mongo_db Added config for history of dgp and wso #748
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_writer.hpp
  plugins/mongo_db/mongo_db_plugin.cpp
  plugins/mongo_db/mongo_db_writer.cpp
Labels: enhancement, medium

#757 cli_wallet list_keys - Added accounts and key types, and filter by account #722
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
Labels: enhancement, question

#654 Fix replay #551
  libraries/chain/CMakeLists.txt
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/database_exceptions.hpp
  plugins/chain/plugin.cpp
Labels: core, enhancement, medium

#760 Api get_content - ints zero init bugfix #746
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/comment_api_object.hpp
  libraries/api/include/golos/api/discussion_helper.hpp
  libraries/chain/include/golos/chain/comment_object.hpp
  plugins/mongo_db/mongo_db_state.cpp
  plugins/social_network/social_network.cpp
Labels: bug, low

#762 cli_wallet list_keys - Structure instead vector of strings #761
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
Labels: cli_wallet, enhancement, low

#766 wallet - Improved propose transaction builder #669
  libraries/wallet/include/golos/wallet/time_converter.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
Labels: cli_wallet, enhancement, low

#773 Fix start of daemon on empty block_log. #772
  plugins/chain/plugin.cpp
Labels: bug, core, high

#776 Mongo_db Hash oids with MD5 instead of SHA1 #767
  plugins/mongo_db/CMakeLists.txt
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_types.hpp
Labels: enhancement, medium, question

#780 Fix get_open_orders cli_wallet command. #770
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/database_api/include/golos/plugins/database_api/plugin.hpp
Labels: bug, cli_wallet, medium

#779 Database replaying improvements #771
  libraries/chain/database.cpp
  plugins/chain/plugin.cpp
Labels: core, enhancement, medium, softfork

#784 Add dockerctl script. #774
  Dockerfile
  share/golosd/docker/Dockerfile-lowmem
  share/golosd/docker/Dockerfile-lowmem-small
  share/golosd/docker/Dockerfile-mongo
  share/golosd/docker/Dockerfile-small
  share/golosd/docker/Dockerfile-testnet
  share/golosd/docker/Dockerfile-testnet-mongo
  share/golosd/golosd.sh
  share/golosd/golosdctl
Labels: enhancement, medium, optional

#785 Remove excessive warnings in log. #775
  plugins/database_api/api.cpp
  plugins/tags/tag_visitor.cpp
Labels: enhancement, low, optional, softfork
