Repository GolosChain/golos, pull requests merged in 2018-05, with the labels that each got.

#601 Create missing account_metadata objects #599
  libraries/chain/database.cpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/config.hpp
  tests/tests/operation_tests.cpp
Labels: bug, core, hardfork, low

#603 Fix pagination in get_discussions_by_blog(). #598
  plugins/social_network/social_network.cpp
Labels: API changes, bug, high

#604 Fix ordered results in get_discussion_by_created(). #600
  plugins/social_network/social_network.cpp
Labels: API changes, bug, high

#605 Fix filtering in get_discussions_by_author_before_date(). #593
  plugins/social_network/social_network.cpp
Labels: API changes, bug, high

#602 Added get_accounts to follow plugin. Refactored shared api objects
  libraries/CMakeLists.txt
  libraries/api/CMakeLists.txt
  libraries/api/include/golos/api/account_api_object.hpp
  libraries/api/include/golos/api/extended_account.hpp
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/database_api/CMakeLists.txt
  plugins/database_api/api.cpp
  plugins/database_api/include/golos/plugins/database_api/api_objects/account_api_object.hpp
  plugins/database_api/include/golos/plugins/database_api/api_objects/witness_api_object.hpp
  plugins/database_api/include/golos/plugins/database_api/plugin.hpp
  plugins/database_api/include/golos/plugins/database_api/state.hpp
  plugins/follow/CMakeLists.txt
  plugins/follow/include/golos/plugins/follow/plugin.hpp
  plugins/follow/plugin.cpp
Labels: API changes, hardfork, low

#596 Created empty API library for shared api_objects. #595
  libraries/CMakeLists.txt
  libraries/api/CMakeLists.txt
Labels: API changes, hardfork, low

#610 Add ability to get received delegations of account #592
  libraries/chain/include/golos/chain/account_object.hpp
  plugins/database_api/api.cpp
  plugins/database_api/include/golos/plugins/database_api/plugin.hpp
Labels: API changes, enhancement, hardfork, low

#615 Fix clang build #611
  libraries/api/CMakeLists.txt
  libraries/api/account_api_object.cpp
  libraries/api/include/golos/api/account_api_object.hpp
Labels: bug, high

#607 Fix start_author in get_discussions_by_comments. #606
  plugins/social_network/discussion_query.cpp
  plugins/social_network/include/golos/plugins/social_network/api_object/discussion_query.hpp
  plugins/social_network/social_network.cpp
Labels: API changes, bug, high

#612 Refactor block_log to mapped file. #524
  libraries/chain/block_log.cpp
  libraries/chain/include/golos/chain/block_log.hpp
Labels: core, enhancement, medium, softfork

#617 Golos v0.17.3
  CMakeLists.txt
  libraries/chain/block_log.cpp
  libraries/chain/include/golos/chain/block_log.hpp
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/private_message/private_message_plugin.cpp
  plugins/social_network/discussion_query.cpp
  plugins/social_network/include/golos/plugins/social_network/api_object/discussion_query.hpp
  plugins/social_network/social_network.cpp
  share/golosd/docker/Dockerfile-lowmem-small
  share/golosd/docker/Dockerfile-small
Labels: bug, core, enhancement, medium

#583 Split comment object into two objects #541
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/steem_object_types.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/follow/plugin.cpp
  plugins/social_network/include/golos/plugins/social_network/api_object/comment_api_object.hpp
  plugins/social_network/include/golos/plugins/social_network/api_object/discussion.hpp
  plugins/social_network/social_network.cpp
  plugins/social_network/tag_visitor.cpp
Labels: core, hardfork, low

#619 Removed unused indices from account_index
  libraries/chain/include/golos/chain/account_object.hpp
Labels: API changes, enhancement, medium

#623 Fix compilation of comment_apply test. #622
  tests/tests/operation_tests.cpp
Labels: bug, high

#621 Update license to MIT. #584
  LICENSE.md
Labels: enhancement

#624 Limit max delegated amount by current voting power #616
  libraries/chain/block_log.cpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/asset.hpp
  tests/tests/operation_tests.cpp
  tests/tests/operation_time_tests.cpp
Labels: bug, core, hardfork, medium

#628 Fix removing of comment_content_object. #627
  libraries/chain/steem_evaluator.cpp
Labels: bug, core, hardfork, high

#620 Witness api plugin implemented #618
  libraries/wallet/CMakeLists.txt
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/database_api/CMakeLists.txt
  plugins/database_api/api.cpp
  plugins/database_api/include/golos/plugins/database_api/api_objects/owner_authority_history_api_object.hpp
  plugins/database_api/include/golos/plugins/database_api/plugin.hpp
  plugins/database_api/include/golos/plugins/database_api/state.hpp
  plugins/witness_api/CMakeLists.txt
  plugins/witness_api/include/golos/plugins/witness_api/api_objects/feed_history_api_object.hpp
  plugins/witness_api/include/golos/plugins/witness_api/api_objects/witness_api_object.hpp
  plugins/witness_api/include/golos/plugins/witness_api/plugin.hpp
  plugins/witness_api/plugin.cpp
  programs/cli_wallet/CMakeLists.txt
  programs/golosd/CMakeLists.txt
  programs/golosd/main.cpp
  share/golosd/config/config.ini
  share/golosd/config/config_debug.ini
  share/golosd/config/config_stock_exchange.ini
  share/golosd/config/config_witness.ini
Labels: API changes, enhancement, medium

#634 Publish transaction builder commands in cli_wallet. #633
  libraries/wallet/include/golos/wallet/wallet.hpp
Labels: bug, core, hardfork, high

#637 Fix malforming builder tx on propose_builder_transaction fail #636
  libraries/wallet/wallet.cpp
  tests/tests/proposal_tests.cpp
Labels: bug, hardfork, medium

#642 Ability to create nesting proposals with cli_wallet #641
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/account_history/include/golos/plugins/account_history/plugin.hpp
Labels: enhancement, hardfork, low

#645 Push proposal transaction #644
  libraries/chain/database.cpp
  libraries/chain/database_proposal_object.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/operation_notification.hpp
  libraries/chain/proposal_evaluator.cpp
  plugins/operation_history/include/golos/plugins/operation_history/history_object.hpp
  plugins/operation_history/plugin.cpp
Labels: bug, hardfork, medium

#649 Added check for tag_index availability in fill_promoted #647
  plugins/tags/plugin.cpp
Labels: API changes, bug, high

#653 Add missing plugins 'tags' into configuration files. #652
  share/golosd/config/config.ini
  share/golosd/config/config_debug.ini
Labels: enhancement, low

#655 Fix posts with empty tags in get_discussions_by_XXX. #648
  plugins/tags/include/golos/plugins/tags/discussion_query.hpp
  plugins/tags/plugin.cpp
  plugins/tags/tag_visitor.cpp
Labels: API changes, bug, low

#656 Fix posts with empty tags in get_discussions_by_XXX. #648
  plugins/social_network/include/golos/plugins/social_network/api_object/discussion_query.hpp
  plugins/social_network/social_network.cpp
  plugins/social_network/tag_visitor.cpp
Labels: API changes, bug, low

#666 Additional validations for proposed transactions. #664
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/proposal_evaluator.cpp
  libraries/protocol/include/golos/protocol/config.hpp
Labels: bug, core, hardfork, high

#667 Empty result instead of error in get_discussions_by_comment. #665
  plugins/tags/plugin.cpp
Labels: API changes, enhancement, low

#675 Optional field reputation. #674
  libraries/api/CMakeLists.txt
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/account_api_object.hpp
  libraries/api/include/golos/api/discussion.hpp
  libraries/api/include/golos/api/discussion_helper.hpp
  libraries/api/include/golos/api/extended_account.hpp
  libraries/api/include/golos/api/vote_state.hpp
  plugins/database_api/CMakeLists.txt
  plugins/database_api/api.cpp
  plugins/database_api/include/golos/plugins/database_api/state.hpp
  plugins/follow/include/golos/plugins/follow/follow_api_object.hpp
  plugins/follow/include/golos/plugins/follow/plugin.hpp
  plugins/follow/plugin.cpp
  plugins/social_network/include/golos/plugins/social_network/social_network.hpp
  plugins/social_network/social_network.cpp
  plugins/tags/include/golos/plugins/tags/plugin.hpp
  plugins/tags/include/golos/plugins/tags/tags_sort.hpp
  plugins/tags/plugin.cpp
  programs/golosd/CMakeLists.txt
  programs/golosd/main.cpp
Labels: API changes, enhancement, medium

#680 Add verification of proposals. #671
  libraries/chain/database.cpp
  libraries/chain/database_proposal_object.cpp
  libraries/chain/fork_database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/proposal_object.hpp
  libraries/chain/proposal_evaluator.cpp
  libraries/chain/proposal_object.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/include/golos/protocol/sign_state.hpp
  libraries/protocol/sign_state.cpp
  libraries/protocol/transaction.cpp
  tests/tests/block_tests.cpp
  tests/tests/operation_tests.cpp
  tests/tests/proposal_tests.cpp
Labels: core, enhancement, hardfork, low

#683 Add votable delegation parameters. #673
  libraries/api/CMakeLists.txt
  libraries/api/chain_api_properties.cpp
  libraries/api/include/golos/api/chain_api_properties.hpp
  libraries/api/include/golos/api/comment_api_object.hpp
  libraries/api/include/golos/api/witness_api_object.hpp
  libraries/api/witness_api_object.cpp
  libraries/chain/CMakeLists.txt
  libraries/chain/chain_properties_evaluators.cpp
  libraries/chain/database.cpp
  libraries/chain/hardfork.d/0_18.hf
  libraries/chain/include/golos/chain/steem_evaluator.hpp
  libraries/chain/include/golos/chain/witness_objects.hpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/operations.hpp
  libraries/protocol/include/golos/protocol/steem_operations.hpp
  libraries/protocol/steem_operations.cpp
  libraries/wallet/wallet.cpp
  plugins/database_api/api.cpp
  plugins/database_api/include/golos/plugins/database_api/plugin.hpp
  plugins/network_broadcast_api/network_broadcast_api.cpp
  plugins/witness/witness.cpp
  plugins/witness_api/CMakeLists.txt
  plugins/witness_api/include/golos/plugins/witness_api/api_objects/witness_api_object.hpp
  plugins/witness_api/include/golos/plugins/witness_api/plugin.hpp
  plugins/witness_api/plugin.cpp
Labels: core, enhancement, hardfork, high

#685 Add the field category in api comment object. #684
  libraries/api/comment_api_object.cpp
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/comment_api_object.hpp
Labels: API changes, enhancement, high
