Repository GolosChain/golos, pull requests merged in 2018-02, with the labels that each got.

#404 add fixed disable compilation warnings
  libraries/plugins/blockchain_statistics/plugin.cpp
  libraries/plugins/social_network/include/golos/plugins/social_network/languages/language_visitor.hpp
  libraries/plugins/social_network/language_visitor.cpp
Labels: bug

#410 406 broadcast transaction with callback
  contribution/config.ini
  libraries/plugins/network_broadcast_api/include/golos/plugins/network_broadcast_api/network_broadcast_api_plugin.hpp
  libraries/plugins/network_broadcast_api/network_broadcast_api.cpp
  libraries/plugins/witness/witness.cpp
Labels: API changes

#405 Add debug node for 16.5
  contribution/config.ini
  libraries/plugins/debug_node/CMakeLists.txt
  libraries/plugins/debug_node/include/golos/plugins/debug_node/plugin.hpp
  libraries/plugins/debug_node/plugin.cpp
  programs/golosd/CMakeLists.txt
  programs/golosd/main.cpp
Labels: API changes, softfork

#411 Plugins format fixed
  libraries/plugins/account_by_key/account_by_key_plugin.cpp
  libraries/plugins/account_by_key/include/golos/plugins/account_by_key/account_by_key_objects.hpp
  libraries/plugins/account_by_key/include/golos/plugins/account_by_key/account_by_key_plugin.hpp
  libraries/plugins/auth_util/include/golos/plugins/auth_util/plugin.hpp
  libraries/plugins/auth_util/plugin.cpp
  libraries/plugins/block_info/include/golos/plugins/block_info/plugin.hpp
  libraries/plugins/block_info/plugin.cpp
  libraries/plugins/follow/plugin.cpp
  libraries/plugins/market_history/market_history_plugin.cpp
  libraries/plugins/private_message/include/golos/plugins/private_message/private_message_objects.hpp
  libraries/plugins/private_message/include/golos/plugins/private_message/private_message_plugin.hpp
  libraries/plugins/private_message/private_message_plugin.cpp
  libraries/plugins/raw_block/include/golos/plugins/raw_block/plugin.hpp
  libraries/plugins/raw_block/plugin.cpp
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
Labels: API changes, softfork

#408 370 tests return to life
  CMakeLists.txt
  Dockerfile
  libraries/chain/database.cpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/asset.hpp
  libraries/protocol/include/golos/protocol/config.hpp
  libraries/protocol/steem_operations.cpp
  plugins/debug_node/include/golos/plugins/debug_node/plugin.hpp
  plugins/debug_node/plugin.cpp
  plugins/json_rpc/include/golos/plugins/json_rpc/utility.hpp
  plugins/json_rpc/plugin.cpp
  share/golosd/docker/Dockerfile-test
  tests/CMakeLists.txt
  tests/README.md
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/plugin_tests/market_history.cpp
  tests/plugin_tests/plugin_ops.cpp
  tests/tests/basic_tests.cpp
  tests/tests/block_tests.cpp
  tests/tests/live_tests.cpp
  tests/tests/operation_tests.cpp
  tests/tests/operation_time_tests.cpp
  tests/tests/serialization_tests.cpp
Labels: softfork
