Repository GolosChain/golos, pull requests merged in 2018-04, with the labels that each got.

#510 Add get_order_book_extended. #507
  plugins/market_history/include/golos/plugins/market_history/market_history_objects.hpp
  plugins/market_history/include/golos/plugins/market_history/market_history_plugin.hpp
  plugins/market_history/market_history_plugin.cpp
Labels: API changes, bug, softfork

#527 Less account history master 17
  CMakeLists.txt
  Dockerfile
  documentation/building.md
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/account_history/plugin.cpp
  plugins/chain/plugin.cpp
  share/golosd/docker/Dockerfile-test
  share/golosd/docker/Dockerfile-testnet
Labels: medium

#463 437 fix some tests
  CMakeLists.txt
  share/golosd/docker/Dockerfile-test
  tests/CMakeLists.txt
  tests/common/comment_reward.hpp
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/plugin_tests/market_history.cpp
  tests/plugin_tests/plugin_ops.cpp
  tests/tests/basic_tests.cpp
  tests/tests/block_tests.cpp
  tests/tests/hf17_tests.cpp
  tests/tests/live_tests.cpp
  tests/tests/operation_tests.cpp
  tests/tests/operation_time_tests.cpp
  tests/tests/serialization_tests.cpp
Labels: API changes, bug, low, softfork

#424 Increased the performance of blockchain statistics plugin
  plugins/blockchain_statistics/plugin.cpp
  plugins/statsd/CMakeLists.txt
  plugins/statsd/include/golos/plugins/statsd/plugin.hpp
  plugins/statsd/include/golos/plugins/statsd/runtime_bucket_object.hpp
  plugins/statsd/include/golos/plugins/statsd/statistics_sender.hpp
  plugins/statsd/plugin.cpp
  plugins/statsd/statistics_sender.cpp
  programs/golosd/CMakeLists.txt
  programs/golosd/main.cpp
  share/golosd/config/config.ini
  share/golosd/config/config_debug.ini
Labels: R&D, optional, softfork

#532 Restore transaction_ids field in cli_wallet get_block command #531
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
Labels: API changes, bug, medium, softfork

#481 Disable old tags plugin functionality for LOW_MEM node
  plugins/social_network/social_network.cpp
Labels: API changes, optional, question, softfork

#537 Fix private_message plugin interface #529
  libraries/protocol/include/golos/protocol/operation_util.hpp
  libraries/protocol/include/golos/protocol/operation_util_impl.hpp
  plugins/follow/include/golos/plugins/follow/follow_operations.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_evaluators.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_objects.hpp
Labels: bug, high, softfork

#546 Add comments to parameters in config.ini. #506
  plugins/account_history/plugin.cpp
  share/golosd/config/config.ini
  share/golosd/config/config_debug.ini
  share/golosd/config/config_stock_exchange.ini
  share/golosd/config/config_witness.ini
Labels: question, softfork

#557 Initial commit for 0.18.0
  libraries/chain/database.cpp
  libraries/chain/hardfork.d/0-preamble.hf
  libraries/chain/hardfork.d/0_18.hf
  libraries/protocol/include/golos/protocol/config.hpp
Labels: core, hardfork

#553 Fixed bug: Witness price feed never expire
  libraries/chain/database.cpp
  libraries/chain/hardfork.d/0_18.hf
Labels: bug, core, hardfork

#558 Forever editable posts and comments
  libraries/chain/hardfork.d/0_18.hf
  libraries/chain/steem_evaluator.cpp
Labels: core, hardfork, low

#576 Refactored get_account_reputations API method in follow plugin
  plugins/follow/include/golos/plugins/follow/plugin.hpp
  plugins/follow/plugin.cpp
Labels: API changes, hardfork, low

#579 Removed extraneous multiindex structs #139
  libraries/chain/include/golos/chain/comment_object.hpp
Labels: core, hardfork, low

#577 Removed category object #124
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/steem_object_types.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/database_api/include/golos/plugins/database_api/state.hpp
  plugins/social_network/CMakeLists.txt
  plugins/social_network/discussion_query.cpp
  plugins/social_network/include/golos/plugins/social_network/api_object/category_api_object.hpp
  plugins/social_network/include/golos/plugins/social_network/api_object/category_index.hpp
  plugins/social_network/include/golos/plugins/social_network/api_object/comment_api_object.hpp
  plugins/social_network/include/golos/plugins/social_network/social_network.hpp
  plugins/social_network/social_network.cpp
  plugins/social_network/tag_visitor.cpp
Labels: API changes, core, hardfork, low

#587 Private message API basic offset #440
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/private_message/private_message_plugin.cpp
Labels: API changes, enhancement

#588 Add Dockerfile-lowmem-small
  share/golosd/docker/Dockerfile-lowmem-small
Labels: enhancement, optional

#575 Removed always empty fields in db api extended account struct
  plugins/database_api/CMakeLists.txt
  plugins/database_api/api.cpp
  plugins/database_api/include/golos/plugins/database_api/state.hpp
Labels: API changes, hardfork, low

#591 Split off json_metadata from account object #196
  libraries/chain/database.cpp
  libraries/chain/hardfork.d/0_18.hf
  libraries/chain/include/golos/chain/account_object.hpp
  libraries/chain/include/golos/chain/steem_evaluator.hpp
  libraries/chain/include/golos/chain/steem_object_types.hpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/operations.hpp
  libraries/protocol/include/golos/protocol/steem_operations.hpp
  libraries/protocol/steem_operations.cpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/account_history/plugin.cpp
  plugins/database_api/include/golos/plugins/database_api/api_objects/account_api_object.hpp
  plugins/statsd/plugin.cpp
  tests/tests/operation_tests.cpp
Labels: API changes, core, hardfork, medium

#594 Added check for emptiness in get_active_witnesses
  plugins/database_api/api.cpp
Labels: API changes, hardfork, low
