Repository GolosChain/golos, pull requests merged in 2018-08, with the labels that each got.

#897 Add option to delete votes older than N blocks #801
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  plugins/chain/include/golos/plugins/chain/plugin.hpp
  plugins/chain/plugin.cpp
  plugins/follow/follow_evaluators.cpp
  plugins/operation_history/plugin.cpp
  plugins/social_network/social_network.cpp
  tests/CMakeLists.txt
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/plugin_tests/account_history.cpp
  tests/plugin_tests/chain.cpp
  tests/plugin_tests/operation_history.cpp
  tests/tests/operation_time_tests.cpp
Labels: API changes, medium, softfork

#896 Refactor errors in database & protocol libraries #792 #793
  libraries/chain/block_log.cpp
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/generic_custom_operation_interpreter.hpp
  libraries/chain/shared_authority.cpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/asset.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/transaction.cpp
  libraries/protocol/types.cpp
  libraries/protocol/version.cpp
Labels: API changes, medium, softfork

#867 Add comment_reward_object to social_network
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/comment_api_object.hpp
  libraries/api/include/golos/api/discussion.hpp
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  plugins/chain/plugin.cpp
  plugins/mongo_db/mongo_db_state.cpp
  plugins/social_network/include/golos/plugins/social_network/social_network_types.hpp
  plugins/social_network/social_network.cpp
  tests/common/comment_reward.hpp
  tests/common/helpers.hpp
  tests/tests/operation_time_tests.cpp
Labels: medium, softfork

#899 Private edit message #807
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/private_message/include/golos/plugins/private_message/private_message_api_objects.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_evaluators.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_exceptions.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_objects.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_operations.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_plugin.hpp
  plugins/private_message/private_message_api_objects.cpp
  plugins/private_message/private_message_operations.cpp
  plugins/private_message/private_message_plugin.cpp
  tests/CMakeLists.txt
  tests/plugin_tests/main.cpp
  tests/plugin_tests/private_message.cpp
Labels: API changes, medium, softfork

#902 Eliminate the inbuilt NTP-client #753
  libraries/time/include/golos/time/time.hpp
  libraries/time/time.cpp
  plugins/witness/witness.cpp
Labels: enhancement, medium, softfork

#905 Fix pending curators payout calculation #903
  libraries/api/discussion_helper.cpp
Labels: bug, medium

#904 Add callbacks for private messages. #806
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/private_message/include/golos/plugins/private_message/private_message_api_objects.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_evaluators.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_exceptions.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_plugin.hpp
  plugins/private_message/private_message_plugin.cpp
  tests/plugin_tests/private_message.cpp
Labels: API changes, medium, softfork

#909 Fix cashout time #908
  libraries/chain/steem_evaluator.cpp
Labels: bug, high

#910 Increase tags limit to 15. #752
  plugins/tags/tag_visitor.cpp
Labels: medium, softfork

#907 Add delete_reblog_operation to follow-plugin #751
  plugins/follow/follow_evaluators.cpp
  plugins/follow/follow_operations.cpp
  plugins/follow/include/golos/plugins/follow/follow_api_object.hpp
  plugins/follow/include/golos/plugins/follow/follow_evaluators.hpp
  plugins/follow/include/golos/plugins/follow/follow_objects.hpp
  plugins/follow/include/golos/plugins/follow/follow_operations.hpp
  plugins/follow/include/golos/plugins/follow/plugin.hpp
  plugins/follow/plugin.cpp
Labels: API changes, medium, softfork

#913 Small mongodb improvements. #912
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_types.hpp
  plugins/mongo_db/mongo_db_operations.cpp
  plugins/mongo_db/mongo_db_plugin.cpp
  plugins/mongo_db/mongo_db_state.cpp
  plugins/mongo_db/mongo_db_types.cpp
  plugins/mongo_db/mongo_db_writer.cpp
Labels: low, softfork

#917 Remove lowmem mode. #914
  .travis.yml
  CMakeLists.txt
  Dockerfile
  documentation/building.md
  libraries/chain/database.cpp
  libraries/chain/steem_evaluator.cpp
  programs/build_helpers/configure_build.py
  share/golosd/docker/Dockerfile-lowmem
  share/golosd/docker/Dockerfile-lowmem-small
  share/golosd/docker/Dockerfile-mongo
  share/golosd/docker/Dockerfile-small
  share/golosd/docker/Dockerfile-test
  share/golosd/docker/Dockerfile-testnet
  share/golosd/docker/Dockerfile-testnet-mongo
  tests/tests/operation_tests.cpp
Labels: low

#919 Add config params #915
  libraries/chain/chain_properties_evaluators.cpp
  plugins/mongo_db/mongo_db_state.cpp
  plugins/social_network/include/golos/plugins/social_network/social_network_types.hpp
  plugins/social_network/social_network.cpp
  share/golosd/config/config.ini
  share/golosd/config/config_debug.ini
  share/golosd/config/config_debug_mongo.ini
  share/golosd/config/config_mongo.ini
  share/golosd/config/config_stock_exchange.ini
  share/golosd/config/config_witness.ini
  tests/tests/operation_time_tests.cpp
Labels: low

#920 Fix cli_wallet help autogeneration #858
  libraries/wallet/CMakeLists.txt
  libraries/wallet/include/golos/wallet/wallet.hpp
Labels: bug, cli_wallet, low

#929 807 fix delete private messages
  plugins/private_message/private_message_plugin.cpp
  share/golosd/config/config_debug.ini
  share/golosd/config/config_stock_exchange.ini
  share/golosd/config/config_witness.ini
Labels: bug, medium

#930 Add configurable tags number. #752
  plugins/tags/discussion_query.cpp
  plugins/tags/include/golos/plugins/tags/discussion_query.hpp
  plugins/tags/include/golos/plugins/tags/tag_visitor.hpp
  plugins/tags/plugin.cpp
  plugins/tags/tag_visitor.cpp
  share/golosd/config/config.ini
  share/golosd/config/config_debug.ini
  share/golosd/config/config_debug_mongo.ini
  share/golosd/config/config_mongo.ini
Labels: medium, softfork

#916 Add comment on reblog in follow-plugin #758
  libraries/api/account_api_object.cpp
  libraries/api/include/golos/api/account_api_object.hpp
  libraries/api/include/golos/api/discussion.hpp
  libraries/api/include/golos/api/reblog_entry.hpp
  plugins/follow/follow_evaluators.cpp
  plugins/follow/follow_operations.cpp
  plugins/follow/include/golos/plugins/follow/follow_api_object.hpp
  plugins/follow/include/golos/plugins/follow/follow_objects.hpp
  plugins/follow/include/golos/plugins/follow/follow_operations.hpp
  plugins/follow/plugin.cpp
  plugins/social_network/include/golos/plugins/social_network/social_network_types.hpp
  plugins/tags/plugin.cpp
Labels: API changes, medium, softfork

#935 Golos v0.18.4
  libraries/api/account_api_object.cpp
  libraries/api/include/golos/api/account_api_object.hpp
  libraries/api/include/golos/api/discussion.hpp
  libraries/api/include/golos/api/reblog_entry.hpp
  plugins/follow/follow_evaluators.cpp
  plugins/follow/follow_operations.cpp
  plugins/follow/include/golos/plugins/follow/follow_api_object.hpp
  plugins/follow/include/golos/plugins/follow/follow_objects.hpp
  plugins/follow/include/golos/plugins/follow/follow_operations.hpp
  plugins/follow/plugin.cpp
  plugins/private_message/private_message_plugin.cpp
  plugins/social_network/include/golos/plugins/social_network/social_network_types.hpp
  plugins/tags/discussion_query.cpp
  plugins/tags/include/golos/plugins/tags/discussion_query.hpp
  plugins/tags/include/golos/plugins/tags/tag_visitor.hpp
  plugins/tags/plugin.cpp
  plugins/tags/tag_visitor.cpp
  programs/js_operation_serializer/CMakeLists.txt
  programs/js_operation_serializer/main.cpp
  share/golosd/config/config.ini
  share/golosd/config/config_debug.ini
  share/golosd/config/config_debug_mongo.ini
  share/golosd/config/config_mongo.ini
  share/golosd/config/config_stock_exchange.ini
  share/golosd/config/config_witness.ini
Labels: medium, softfork

#938 chain_properties_19 #295
  libraries/api/chain_api_properties.cpp
  libraries/api/include/golos/api/chain_api_properties.hpp
  libraries/chain/chain_properties_evaluators.cpp
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/witness_objects.hpp
  libraries/protocol/include/golos/protocol/config.hpp
  libraries/protocol/include/golos/protocol/steem_operations.hpp
  libraries/protocol/include/golos/protocol/validate_helper.hpp
  libraries/protocol/steem_operations.cpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
Labels: core, hardfork, high

#945 Added annotated_signed_block #936
  libraries/api/CMakeLists.txt
  libraries/api/block_objects.cpp
  libraries/api/include/golos/api/block_objects.hpp
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/database_api/api.cpp
  plugins/operation_history/CMakeLists.txt
  plugins/operation_history/include/golos/plugins/operation_history/plugin.hpp
  plugins/operation_history/plugin.cpp
Labels: API changes, medium, softfork

#944 Fixed set_program_options bug. #943
  plugins/account_history/plugin.cpp
  plugins/debug_node/plugin.cpp
  plugins/follow/plugin.cpp
  plugins/market_history/market_history_plugin.cpp
  plugins/mongo_db/mongo_db_plugin.cpp
  plugins/operation_history/plugin.cpp
  plugins/statsd/plugin.cpp
  plugins/witness/witness.cpp
Labels: bug
