Repository GolosChain/golos, pull requests merged in 2018-07, with the labels that each got.

#781 Get discussions by created fix #768
  plugins/tags/plugin.cpp
Labels: API changes, bug, medium, softfork

#795 Golos v0.18.1
  Dockerfile
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/comment_api_object.hpp
  libraries/api/include/golos/api/discussion_helper.hpp
  libraries/chain/CMakeLists.txt
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/database_exceptions.hpp
  libraries/protocol/include/golos/protocol/config.hpp
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/time_converter.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/chain/plugin.cpp
  plugins/database_api/api.cpp
  plugins/database_api/include/golos/plugins/database_api/plugin.hpp
  plugins/mongo_db/CMakeLists.txt
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_types.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_writer.hpp
  plugins/mongo_db/mongo_db_plugin.cpp
  plugins/mongo_db/mongo_db_state.cpp
  plugins/mongo_db/mongo_db_writer.cpp
  plugins/social_network/social_network.cpp
  plugins/tags/plugin.cpp
  plugins/tags/tag_visitor.cpp
  share/golosd/docker/Dockerfile-lowmem
  share/golosd/docker/Dockerfile-lowmem-small
  share/golosd/docker/Dockerfile-mongo
  share/golosd/docker/Dockerfile-small
  share/golosd/docker/Dockerfile-testnet
  share/golosd/docker/Dockerfile-testnet-mongo
  share/golosd/golosd.sh
  share/golosd/golosdctl
Labels: softfork

#812 Add to config list of accounts to store metadata in db, mongo #794
  libraries/api/account_api_object.cpp
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/chain/plugin.cpp
  plugins/mongo_db/mongo_db_state.cpp
  tests/CMakeLists.txt
  tests/tests/operation_tests.cpp
Labels: medium, softfork

#778 Improve history ops filters usability #668
  plugins/account_history/include/golos/plugins/account_history/history_object.hpp
  plugins/account_history/plugin.cpp
  plugins/operation_history/include/golos/plugins/operation_history/plugin.hpp
  plugins/operation_history/plugin.cpp
  share/golosd/docker/Dockerfile-test
  tests/CMakeLists.txt
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/common/options_fixture.cpp
  tests/common/options_fixture.hpp
  tests/plugin_tests/account_history_blocks_test.cpp
  tests/plugin_tests/black_options_postfix.cpp
  tests/plugin_tests/operation_history_blocks_test.cpp
  tests/plugin_tests/plugin_ops.cpp
  tests/plugin_tests/short_list_operation_postfix_test.cpp
  tests/plugin_tests/white_options_postfix.cpp
Labels: enhancement, medium, optional

#819 Remove LOW_MEM from tags plugin #798
  plugins/social_network/social_network.cpp
  plugins/tags/plugin.cpp
Labels: medium, softfork

#822 Add config flag to storing memo for transfers #797
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/steem_object_types.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/chain/plugin.cpp
  plugins/mongo_db/mongo_db_state.cpp
  tests/tests/operation_tests.cpp
Labels: medium, softfork

#831 cli_wallet Fix signing of transactions when another account_auths #699
  libraries/wallet/wallet.cpp
Labels: bug, cli_wallet, medium

#832 786 base exceptions and macros for errors handling
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database_exceptions.hpp
  libraries/chain/include/golos/chain/steem_evaluator.hpp
  libraries/chain/steem_evaluator.cpp
  libraries/network/include/golos/network/exceptions.hpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/proposal_operations.cpp
  libraries/protocol/steem_operations.cpp
  plugins/json_rpc/CMakeLists.txt
  plugins/json_rpc/include/golos/plugins/json_rpc/plugin.hpp
  plugins/json_rpc/include/golos/plugins/json_rpc/utility.hpp
  plugins/json_rpc/plugin.cpp
  plugins/market_history/market_history_plugin.cpp
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/tests/operation_tests.cpp
  tests/tests/proposal_tests.cpp
Labels: API changes, medium, softfork

#835 Fix wintness scheduler for testnet. #834
  libraries/chain/database.cpp
Labels: bug, low

#837 Mongo_db transfer and fill transfer collections, etc. #830 #833
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/mongo_db_plugin.cpp
  plugins/mongo_db/mongo_db_state.cpp
Labels: medium, softfork

#836 Implement convertion from exceptions into JSON response #788
  libraries/protocol/include/golos/protocol/exceptions.hpp
  plugins/json_rpc/include/golos/plugins/json_rpc/plugin.hpp
  plugins/json_rpc/plugin.cpp
  tests/CMakeLists.txt
  tests/plugin_tests/json_rpc.cpp
Labels: API changes, medium, softfork

#839 Better api callbacks + producer_reward virtual op #743
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/operation_notification.hpp
  libraries/protocol/include/golos/protocol/block.hpp
  libraries/protocol/include/golos/protocol/operations.hpp
  libraries/protocol/include/golos/protocol/steem_virtual_operations.hpp
  libraries/protocol/include/golos/protocol/transaction.hpp
  libraries/wallet/wallet.cpp
  plugins/account_history/plugin.cpp
  plugins/database_api/api.cpp
  plugins/database_api/include/golos/plugins/database_api/plugin.hpp
  plugins/json_rpc/include/golos/plugins/json_rpc/utility.hpp
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/tests/operation_time_tests.cpp
Labels: API changes, medium, softfork

#842 786 remove usage of internal boost test objects
  tests/common/database_fixture.hpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#840 Remove IS_LOW_MEM around comment_object::parent #799
  libraries/chain/database.cpp
  libraries/chain/steem_evaluator.cpp
Labels: medium, softfork

#838 796 add depth history for storing comment contents
  libraries/api/CMakeLists.txt
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/comment_api_object.hpp
  libraries/api/include/golos/api/discussion.hpp
  libraries/api/include/golos/api/discussion_helper.hpp
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/steem_object_types.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/follow/CMakeLists.txt
  plugins/follow/include/golos/plugins/follow/plugin.hpp
  plugins/follow/plugin.cpp
  plugins/social_network/include/golos/plugins/social_network/comment_content_object.hpp
  plugins/social_network/include/golos/plugins/social_network/social_network.hpp
  plugins/social_network/social_network.cpp
  plugins/tags/include/golos/plugins/tags/tag_visitor.hpp
  plugins/tags/plugin.cpp
  plugins/tags/tag_visitor.cpp
  tests/CMakeLists.txt
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/tests/operation_tests.cpp
Labels: enhancement, softfork

#845 Refactor errors: vote_operation #790
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#856 Private message add missing parts of protocol. #805
  libraries/wallet/include/golos/wallet/time_converter.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/private_message/include/golos/plugins/private_message/private_message_evaluators.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_objects.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_plugin.hpp
  plugins/private_message/private_message_objects.cpp
  plugins/private_message/private_message_plugin.cpp
Labels: API changes, medium, softfork

#857 Refactor errors: common macros #790
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/include/golos/protocol/validate_helper.hpp
  libraries/protocol/steem_operations.cpp
  tests/common/database_fixture.hpp
  tests/common/helpers.hpp
  tests/tests/proposal_tests.cpp
Labels: API changes, medium, softfork

#859 Refactor errors: limit_order_create, limit_order_cancel, limit_order_create2 operations #790
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/asset.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  libraries/protocol/transaction.cpp
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#862 Refactor errors: update log printers #790
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/common/helpers.hpp
Labels: API changes, medium, softfork

#865 Refactor errors: macro for trivial ErrorValidator generation #790
  tests/common/database_fixture.hpp
  tests/common/helpers.hpp
Labels: API changes, medium, softfork

#869 Refactor errors: convert_operation #790
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#872 Refactor errors: report_over_production_operation #790
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/steem_operations.cpp
Labels: API changes, medium, softfork

#870 Refactor errors: custom, custom_json and custom_binary operations #790
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/authority.cpp
  libraries/protocol/steem_operations.cpp
  tests/common/database_fixture.hpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#868 Refactor errors: account_witness_vote & account_witness_proxy operations
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#873 Refactor errors: delete_comment_operation #790
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  tests/common/helpers.hpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#874 Refactor errors: decline_voting_rights + disabled reset_account, set_reset_account #790
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  tests/common/database_fixture.hpp
  tests/tests/operation_tests.cpp
  tests/tests/proposal_tests.cpp
Labels: API changes, medium, softfork

#879 Refactor errors: fix delete_comment_operation #790
  tests/tests/operation_tests.cpp
Labels: API changes, high, softfork

#878 Refactor errors: transfer_to/from_savings operations #790
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/steem_operations.cpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#881 Refactor errors: pow & pow2 operations #790
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
Labels: API changes, medium, softfork

#883 Refactor errors: account recovery operations #790
  libraries/chain/database.cpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#884 Refactor errors: escrow_transfer & escrow_approve operations #790
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#887 Refactor database_fixture to simplify plugins tests #791
  libraries/chain/include/golos/chain/database.hpp
  plugins/chain/include/golos/plugins/chain/plugin.hpp
  plugins/chain/plugin.cpp
  plugins/operation_history/plugin.cpp
  share/golosd/docker/Dockerfile-test
  tests/CMakeLists.txt
  tests/common/database_fixture.cpp
  tests/common/database_fixture.hpp
  tests/common/options_fixture.cpp
  tests/common/options_fixture.hpp
  tests/plugin_tests/account_history.cpp
  tests/plugin_tests/account_history_blocks_test.cpp
  tests/plugin_tests/black_options_postfix.cpp
  tests/plugin_tests/operation_history.cpp
  tests/plugin_tests/operation_history_blocks_test.cpp
  tests/plugin_tests/short_list_operation_postfix_test.cpp
  tests/plugin_tests/white_options_postfix.cpp
Labels: API changes, medium, softfork

#875 Refactor errors: comment_options_operation #790
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/exceptions.hpp
  libraries/protocol/steem_operations.cpp
  tests/tests/operation_tests.cpp
Labels: API changes, medium, softfork

#890 860 clear comment content
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/discussion_helper.hpp
  plugins/follow/plugin.cpp
  plugins/social_network/include/golos/plugins/social_network/social_network.hpp
  plugins/social_network/social_network.cpp
  plugins/tags/discussion_query.cpp
  plugins/tags/include/golos/plugins/tags/tag_visitor.hpp
  plugins/tags/include/golos/plugins/tags/tags_object.hpp
  plugins/tags/plugin.cpp
  plugins/tags/tag_visitor.cpp
Labels: bug, high

#894 Private contact list #805
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/private_message/CMakeLists.txt
  plugins/private_message/include/golos/plugins/private_message/private_message_api_objects.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_evaluators.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_exceptions.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_objects.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_operations.hpp
  plugins/private_message/include/golos/plugins/private_message/private_message_plugin.hpp
  plugins/private_message/private_message_api_objects.cpp
  plugins/private_message/private_message_objects.cpp
  plugins/private_message/private_message_operations.cpp
  plugins/private_message/private_message_plugin.cpp
Labels: API changes, medium, softfork

#888 Add comment_last_update_object to social_network-plugin #828
  libraries/api/comment_api_object.cpp
  libraries/api/discussion_helper.cpp
  libraries/api/include/golos/api/comment_api_object.hpp
  libraries/api/include/golos/api/discussion_helper.hpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/follow/plugin.cpp
  plugins/mongo_db/CMakeLists.txt
  plugins/mongo_db/mongo_db_state.cpp
  plugins/social_network/include/golos/plugins/social_network/comment_content_object.hpp
  plugins/social_network/include/golos/plugins/social_network/social_network.hpp
  plugins/social_network/include/golos/plugins/social_network/social_network_types.hpp
  plugins/social_network/social_network.cpp
  plugins/tags/CMakeLists.txt
  plugins/tags/include/golos/plugins/tags/tag_visitor.hpp
  plugins/tags/include/golos/plugins/tags/tags_sort.hpp
  plugins/tags/plugin.cpp
  plugins/tags/tag_visitor.cpp
  tests/tests/operation_tests.cpp
Labels: medium, softfork

#895 Refactor errors: cli_wallet #804
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
Labels: API changes, medium, softfork

#900 Refactor errors: remove PLUGIN_CHECK_LOGIC from follow plugin #791
  plugins/follow/follow_evaluators.cpp
  plugins/follow/follow_operations.cpp
  plugins/follow/include/golos/plugins/follow/plugin.hpp
Labels: API changes, medium, softfork
