Repository GolosChain/golos, pull requests merged in 2018-03, with the labels that each got.

#441 Implement linear reward curve for HF17. #433
  libraries/chain/database.cpp
  libraries/chain/hardfork.d/0_17.hf
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/social_network/include/golos/plugins/social_network/api_object/comment_api_object.hpp
  plugins/social_network/social_network.cpp
  tests/tests/operation_tests.cpp
Labels: core, hardfork

#449 Remove stop time for linear reward curve. #447
  libraries/chain/database.cpp
  libraries/chain/hardfork.d/0_17.hf
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/reward_curve.hpp
  libraries/chain/include/golos/chain/steem_object_types.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/social_network/include/golos/plugins/social_network/api_object/comment_api_object.hpp
  plugins/social_network/social_network.cpp
  tests/tests/operation_tests.cpp
  tests/tests/operation_time_tests.cpp
Labels: core, hardfork

#453 Recalculate rshares2 on switch to hf17 #452
  libraries/chain/database.cpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/include/golos/chain/reward_curve.hpp
  libraries/chain/include/golos/chain/steem_object_types.hpp
  libraries/chain/steem_evaluator.cpp
  plugins/social_network/include/golos/plugins/social_network/api_object/comment_api_object.hpp
  plugins/social_network/social_network.cpp
  tests/tests/operation_tests.cpp
Labels: core, hardfork

#455 Increase upvote lockout. #454
  libraries/chain/hardfork.d/0_17.hf
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/get_config.cpp
  libraries/protocol/include/golos/protocol/config.hpp
  tests/tests/operation_tests.cpp
  tests/tests/operation_time_tests.cpp
Labels: core, hardfork

#460 Fix strange errors on parallel get blocks. #459
  libraries/chain/block_log.cpp
  plugins/database_api/api.cpp
  plugins/json_rpc/include/golos/plugins/json_rpc/utility.hpp
  plugins/json_rpc/plugin.cpp
  plugins/webserver/webserver_plugin.cpp
Labels: API changes, bug, critical

#465 Add API social_network::get_all_content_replies. #464
  plugins/social_network/include/golos/plugins/social_network/social_network.hpp
  plugins/social_network/social_network.cpp
Labels: API changes

#467 Golos v0.17.0
  libraries/chain/block_log.cpp
  libraries/chain/database.cpp
  libraries/chain/hardfork.d/0-preamble.hf
  libraries/chain/hardfork.d/0_17.hf
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/include/golos/chain/database.hpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/config.hpp
  libraries/protocol/include/golos/protocol/operations.hpp
  libraries/protocol/include/golos/protocol/steem_operations.hpp
  libraries/protocol/include/golos/protocol/steem_virtual_operations.hpp
  libraries/protocol/steem_operations.cpp
  plugins/account_history/plugin.cpp
  plugins/database_api/api.cpp
  plugins/debug_node/plugin.cpp
  plugins/follow/plugin.cpp
  plugins/json_rpc/include/golos/plugins/json_rpc/utility.hpp
  plugins/json_rpc/plugin.cpp
  plugins/market_history/include/golos/plugins/market_history/market_history_objects.hpp
  plugins/social_network/include/golos/plugins/social_network/api_object/comment_api_object.hpp
  plugins/social_network/include/golos/plugins/social_network/social_network.hpp
  plugins/social_network/social_network.cpp
  plugins/webserver/webserver_plugin.cpp
  share/golosd/config/config.ini
  share/golosd/docker/Dockerfile-test
  tests/tests/hf17_tests.cpp
  tests/tests/operation_tests.cpp
  tests/tests/operation_time_tests.cpp
Labels: hardfork, high

#476 Fix the call list_my_accounts() in cli_wallet. #474
  libraries/wallet/include/golos/wallet/remote_node_api.hpp
  libraries/wallet/wallet.cpp
  plugins/database_api/include/golos/plugins/database_api/plugin.hpp
Labels: bug, high

#480 Fix result of follow::get_following(). #477
  plugins/follow/plugin.cpp
Labels: bug, high

#486 Add field 'mode' to comment_api_object. #479
  plugins/social_network/include/golos/plugins/social_network/api_object/comment_api_object.hpp
Labels: bug, medium

#490 Set field 'reputation' in get_accounts(). #470
  plugins/database_api/CMakeLists.txt
  plugins/database_api/api.cpp
  plugins/database_api/include/golos/plugins/database_api/plugin.hpp
  plugins/social_network/social_network.cpp
Labels: bug, medium
