Repository GolosChain/golos, pull requests merged in 2019-05, with the labels that each got.

#1305 Fix operation dump votes order #1303
  plugins/operation_dump/include/golos/plugins/operation_dump/operation_dump_plugin.hpp
  plugins/operation_dump/include/golos/plugins/operation_dump/operation_dump_visitor.hpp
  plugins/operation_dump/operation_dump_plugin.cpp
Labels: bug, high

#1308 Fix deletes in operation dump #1306
  libraries/protocol/include/golos/protocol/operations.hpp
  libraries/protocol/include/golos/protocol/steem_virtual_operations.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_operations.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/mongo_db_operations.cpp
  plugins/mongo_db/mongo_db_state.cpp
  plugins/operation_dump/include/golos/plugins/operation_dump/operation_dump_visitor.hpp
  plugins/operation_dump/operation_dump_plugin.cpp
Labels: bug, high

#1310 Fix worker proposal edit, and test it #1307
  libraries/chain/worker_evaluators.cpp
  tests/tests/worker_proposal_tests.cpp
Labels: bug, hardfork

#1314 Fix votes and comment deletes in operation_dump-plugin #1313 #1303 #1306
  libraries/protocol/include/golos/protocol/operations.hpp
  libraries/protocol/include/golos/protocol/steem_virtual_operations.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_operations.hpp
  plugins/mongo_db/include/golos/plugins/mongo_db/mongo_db_state.hpp
  plugins/mongo_db/mongo_db_operations.cpp
  plugins/mongo_db/mongo_db_state.cpp
  plugins/operation_dump/include/golos/plugins/operation_dump/operation_dump_container.hpp
  plugins/operation_dump/include/golos/plugins/operation_dump/operation_dump_plugin.hpp
  plugins/operation_dump/include/golos/plugins/operation_dump/operation_dump_visitor.hpp
  plugins/operation_dump/operation_dump_plugin.cpp
Labels: bug, high

#1311 Add worker cashout tests #1282
  tests/common/comment_reward.hpp
  tests/plugin_tests/worker_api_payment.cpp
  tests/tests/worker_payment_tests.cpp
  tests/tests/worker_techspec_tests.cpp
Labels: tests

#1318 Finish worker result tests #1284
  tests/tests/worker_result_tests.cpp
Labels: tests

#1320 Forbid create worker results on archived posts #1319
  libraries/chain/worker_evaluators.cpp
Labels: bug, hardfork

#1316 Payout strategy for delegate vesting shares #1045 #1041
  libraries/chain/database.cpp
  libraries/chain/hardfork.d/0_21.hf
  libraries/chain/include/golos/chain/account_object.hpp
  libraries/chain/include/golos/chain/comment_object.hpp
  libraries/chain/steem_evaluator.cpp
  libraries/protocol/include/golos/protocol/steem_operations.hpp
  libraries/protocol/steem_operations.cpp
  libraries/wallet/include/golos/wallet/wallet.hpp
  libraries/wallet/wallet.cpp
  plugins/account_history/plugin.cpp
  plugins/mongo_db/mongo_db_state.cpp
  tests/tests/operation_tests.cpp
Labels: bug, hardfork
